name: Build NumWorks Doom

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

      - name: Compile Application
        run: |
          # On force la liste des fichiers sources pour être sûr que rien n'est oublié
          export SRCS="$(find src -name "*.cpp" -o -name "*.c")"
          make build SRCS="$SRCS"

      - name: Save NWA file
        uses: actions/upload-artifact@v4
        with:
          name: nw-doom-app
          path: "**/*.nwa"
