name: Build NumWorks Doom

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

      - name: Install nwlink
        run: |
          npm install -g nwlink

      - name: Compile Application
        run: |
          make clean
          
          # On cherche les fichiers dans 'src' ET dans 'originalSource'
          # On s'assure de bien tous les lister sur une seule ligne
          SOURCES=$(find src originalSource -name "*.cpp" -o -name "*.c" | tr '\n' ' ')
          
          echo "Fichiers à compiler : $SOURCES"
          
          # On lance le build en forçant SRCS et en ajoutant les chemins d'inclusion pour les .h
          make build SRCS="$SOURCES" USER_FLAGS="-Isrc -IoriginalSource"

      - name: Save NWA file
        uses: actions/upload-artifact@v4
        with:
          name: nw-doom-app
          path: "**/*.nwa"
